#!/bin/bash
# Adding dashboard charts from users


mysql --user=root --password=swords activeagenda -e  " \
INSERT IGNORE INTO dsbc( UserID, ModuleID, ChartName, SortOrder, _ModBy, _ModDate ) \
SELECT PersonID, '$3', '$4', $5, 1, now()  FROM usr \
WHERE PersonID BETWEEN $1 AND $2 and _Deleted=0"



