#!/bin/bash

# Setting the right owner and persmissions on debian and Apache2

AA_PATH=/var/www/s2a 

chown -R  www-data:www-data $AA_PATH
chmod 775 $AA_PATH
chmod -R 444 $AA_PATH/*
find $AA_PATH -type d | xargs chmod 744

chown -R root:root $AA_PATH/util
chmod 774 $AA_PATH/util/aa-* 

chown -R root:root $AA_PATH/lib/cron/
chmod 744 $AA_PATH/lib/cron/cron-*.php
chmod 644 $AA_PATH/lib/cron/activeagenda 

if [ ! -e $AA_PATH/active_agenda/uploads ]
then
    mkdir $AA_PATH/active_agenda/uploads 
fi
chown www-data:www-data $AA_PATH/active_agenda/uploads 
chmod 774 $AA_PATH/active_agenda/uploads 

chmod -R 774 $AA_PATH/active_agenda/s2alog 

chown -R root:root  $AA_PATH/active_agenda/xml 
chmod 664 $AA_PATH/active_agenda/xml 

if [ -e $AA_PATH/active_agenda/.generated ]
then
    mv $AA_PATH/active_agenda/.generated $AA_PATH/active_agenda/generated
fi